const ProductActionTypes ={
    FETCH_GET_CATEGORY_START:'FETCH_GET_CATEGORY_START',
    FETCH_GET_CATEGORY_SUCCESS:'FETCH_GET_CATEGORY_SUCCESS',
    FETCH_GET_CATEGORY_FAILURE:'FETCH_GET_CATEGORY_FAILURE',
    FETCH_CREATE_CATEGORY_START:'FETCH_CREATE_CATEGORY_START',
    FETCH_CREATE_CATEGORY_SUCCESS:'FETCH_CREATE_CATEGORY_SUCCESS',
    FETCH_CREATE_CATEGORY_FAILURE:'FETCH_CREATE_CATEGORY_FAILURE',
    FETCH_UPDATE_CATEGORY_START:'FETCH_UPDATE_CATEGORY_START',
    FETCH_UPDATE_CATEGORY_SUCCESS:'FETCH_UPDATE_CATEGORY_SUCCESS',
    FETCH_UPDATE_CATEGORY_FAILURE:'FETCH_UPDATE_CATEGORY_FAILURE',
    FETCH_DELETE_CATEGORY_START:'FETCH_DELETE_CATEGORY_START',
    FETCH_DELETE_CATEGORY_SUCCESS:'FETCH_DELETE_CATEGORY_SUCCESS',
    FETCH_DELETE_CATEGORY_FAILURE:'FETCH_DELETE_CATEGORY_FAILURE',
}

export default ProductActionTypes;
