 const UserActionTypes ={
    FETCH_AUTENTICATION_START: 'FETCH_AUTENTICATION_START',
    FETCH_AUTENTICATION_SUCCESS: 'FETCH_AUTENTICATION_SUCCESS',
    FETCH_AUTENTICATION_FAILURE: 'FETCH_AUTENTICATION_FAILURE',
    FETCH_AUTENTICATION_DENIED: 'FETCH_AUTENTICATION_DENIED',
}

export default UserActionTypes;