const ProductActionTypes ={
    FETCH_CREATE_PRODUCTS_START:'FETCH_CREATE_PRODUCTS_START',
    FETCH_CREATE_PRODUCTS_SUCCESS:'FETCH_CREATE_PRODUCTS_SUCCESS',
    FETCH_CREATE_PRODUCTS_FAILURE:'FETCH_CREATE_PRODUCTS_FAILURE',
    FETCH_GET_PRODUCTS_START:'FETCH_GET_PRODUCTS_START',
    FETCH_GET_PRODUCTS_SUCCESS:'FETCH_GET_PRODUCTS_SUCCESS',
    FETCH_GET_PRODUCTS_FAILURE:'FETCH_GET_PRODUCTS_FAILURE',
    FETCH_UPDATE_PRODUCTS_START:'FETCH_UPDATE_PRODUCTS_START',
    FETCH_UPDATE_PRODUCTS_SUCCESS:'FETCH_UPDATE_PRODUCTS_SUCCESS',
    FETCH_UPDATE_PRODUCTS_FAILURE:'FETCH_UPDATE_PRODUCTS_FAILURE',
    FETCH_DELETE_PRODUCTS_START:'FETCH_DELETE_PRODUCTS_START',
    FETCH_DELETE_PRODUCTS_SUCCESS:'FETCH_DELETE_PRODUCTS_SUCCESS',
    FETCH_DELETE_PRODUCTS_FAILURE:'FETCH_DELETE_PRODUCTS_FAILURE',
    SET_ACTION_SUCCESS:'SET_ACTION_SUCCESS',
    SET_ACTION_FAILURE:'SET_ACTION_FAILURE',
    SET_ACTION_COMPLETE: 'SET_ACTION_COMPLETE',
}

export default ProductActionTypes;
