const ProductActionTypes ={
    FETCH_CREATE_PRODUCTS_START:'FETCH_CREATE_PRODUCTS_START',
    FETCH_CREATE_PRODUCTS_SUCCESS:'FETCH_CREATE_PRODUCTS_START',
    FETCH_CREATE_PRODUCTS_FAILURE:'FETCH_CREATE_PRODUCTS_FAILURE',
    FETCH_GET_PRODUCTS_START:'FETCH_GET_PRODUCTS_START',
    FETCH_GET_PRODUCTS_SUCCESS:'FETCH_GET_PRODUCTS_SUCCESS',
    FETCH_GET_PRODUCTS_FAILURE:'FETCH_GET_PRODUCTS_FAILURE',
}

export default ProductActionTypes;